export const constants = {
  IMAGE_FOLDER_SKINS: 'assets/dream-smp-skins',
  IMAGES_FOLDER_FACE: 'assets/dream-smp-skins/face',
  IMAGES_FOLDER_FULL_BODY: 'assets/dream-smp-skins/full-body',
  IMAGES_FOLDER_HALF_BODY: 'assets/dream-smp-skins/half-body',
  IMAGES_FOLDER_MC_TEXTURES: 'assets/minecraft-textures',
  IMAGES_FOLDER_MC_STEVE: 'assets/minecraft-steve',
  
  FILE_EMPTY_BODY: 'empty-body.png',
  FILE_OFFLINE_FACE: 'minecraft-steve-face.png',
  FILE_OFFLINE_FULL_BODY: 'minecraft-steve-full-body.png',
  FILE_OFFLINE_HALF_BODY: 'minecraft-steve-half-body.png',
  
  RAW_FOLDER: 'data/raw',
  GRAPH_FOLDER: 'data/graph',
  GRAPH_DIAMETER: 370,
  
  GRAPH_HOVER_TEXT_DIAMETER: 400,
  GRAPH_HOVER_TEXT_FONT_SIZE: '16px',
  GRAPH_HOVER_TEXT_DY: 8,
  
  GRAPH_HOVER_HEART_FULL: 'heart-full.svg',
  GRAPH_HOVER_HEART_HALF: 'heart-half.svg',
  GRAPH_HOVER_HEART_EMPTY: 'heart-empty.svg',
  GRAPH_HOVER_HEART_WIDTH: 25, // w:h = 1:1
  GRAPH_HOVER_HEART_HEIGHT: 25,
  GRAPH_HOVER_HEART_DY: -3,
  GRAPH_HOVER_HEART_NUM: 5,
  
  GRAPH_HOVER_BODY_WIDTH: 33,
  GRAPH_HOVER_BODY_HEIGHT: 44, // w:h = 3:4
  GRAPH_HOVER_BODY_DY: -8,
  GRAPH_HOVER_BODY_NUM: 5,
  
  MAX_NODE_VIEWER_CAP: 250000,
  MAX_LINK_DELTAVIEWER_CAP: 250000, 
  
  NODE_DIAMETER_MIN: 35,  
  NODE_DIAMETER_MAX: 110, 
  NODE_FONT_SIZE: '12px',
  NODE_TEXT_DY_UP: '-2em',
  NODE_TEXT_DY_DOWN: '2.5em',
  NODE_ONLINE_OPACITY: 1,
  NODE_MIDDLE_OPACITY: 0.65,
  NODE_OFFLINE_OPACITY: 0.1, 
  NODE_OFFLINE_DY: -45,
  NODE_OFFLINE_BORDER_DY: -28,
  NODE_OFFLINE_WIDTH_DX: 40,
  NODE_OFFLINE_HEIGHT_DY: 5,
  
  LINK_TENSION: 0.45,
  LINK_OPACITY: 0.5,
  LINK_THICKNESS_MIN: 3,
  LINK_THICKNESS_MAX_PERCENTAGE: 0.9,
  LINK_COLOR: 'grey',
  LINK_INBOUND_COLOR: 'green',
  LINK_OUTBOUND_COLOR: 'red',
  LINK_OFFLINE_DY: -55,
  
  SLIDER_Y: 0,
  SLIDER_TEXT_DX: -18,
  SLIDER_TEXT_Y: -20,
  SLIDER_TEXT_FONT_SIZE_TOP: '14px',
  SLIDER_TEXT_FONT_SIZE_BOTTOM: '14px',
  SLIDER_DATETIME_TEXT_FONT_SIZE: '23px',
  SLIDER_HANDLE_IMAGE: 'grass-block.png',
  SLIDER_HANDLE_IMAGE_WIDTH: 35,
  SLIDER_ANIMATION_INTERVAL: 1000, // millisec
  
  LEGEND_FONT_SIZE: '12px',
  LEGEND_TEXT_DX: 10,
  LEGEND_TITLE_DY: -15,
  
  LEGEND_NODE_IMAGE_OPACITY: 0.65,
  LEGEND_NODE_NUM_VALUES: 5,
  LEGEND_NODE_X: 590, 
  LEGEND_NODE_Y: 100,
  
  LEGEND_LINK_HEIGHT: 110,
  LEGEND_LINK_NUM_VALUES: 5,
  LEGEND_LINK_X: -550, 
  LEGEND_LINK_Y: 100
}